### ISSUE TITLE
 Could not resolve host: 'http   

### ISSUE THREAD

**Issue by Nikhilbharadwaj08** [jrosebr1/simple-keras-rest-api#13]
after this cmd ( curl -X POST -F image=@dog.jpg 'http://localhost:5000/predict')
i;m getting the following error
how to overcome with this..???

**Comment by jrosebr1** [comment]
It sounds like you forgot to launch your Flask server. Double-check that the Flask server script is running.

**Comment by Nikhilbharadwaj08** [comment]
no actually i have set my system DNS manually  to 8.8.8.8, later after
changing to automatic its working fine
thanks man
cheers
